### PR TITLE
remove debug setting

### LINKED ISSUE #29: enhancement: remove the "debug" settings
I realized that the debug log level is already handled by kodi settings, so the "debug" settings in the addon is redundant.

Given that the current debug message are a few and infrequent, there's no need to check the current loglevel, we can directly send the debug message and let kodi handle it.

A PR will follow with the proposed changes

### PR DESCRIPTION
**Pull request by sanzoghenzo**
closes #29

### CODE REVIEW

**Comment by Lord-Grey** [comment]
@sanzoghenzo would it be ok for you to update the version in addon.yml to 20.0.1 and update the what’s new info,please?
Then we can issue a new realeres to the Kodi repository and test the latest workflow having everything consistent.

**Comment by sanzoghenzo** [comment]
Do you think this (non)feature is enough to create a new release?

Anyway, I didn't test the effects of the missing settings after updating to this version;  It shouldn't be a problem, but I'll try it and let you know  ASAP!

**Comment by sanzoghenzo** [comment]
Ok, the test was quicker than expected, it works without problems. Updating the addon manifest...

**Comment by sanzoghenzo** [comment]
Ready to be merged!

**Comment by Lord-Grey** [comment]
> Do you think this (non)feature is enough to create a new release?

In general, I agree.
I only wanted to do this Release to align the release with the versioning scheme (20 = Nexus), include the feedback by team Kodi and test the overall release and Kodi-PR workflow.
-> just build a proper release baseline for upcoming changes

**Pull request merged**
